name: Daily FoFa Search

on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  search:
    runs-on: ubuntu-latest
    steps:  
    - uses: actions/checkout@v2

    - name: Install FoFaX
      run: |
        # 获取最新版本的下载 URL
        DOWNLOAD_URL=$(curl -s https://api.github.com/repos/xiecat/fofax/releases/latest | grep "browser_download_url.*linux_amd64" | cut -d : -f 2,3 | tr -d \")
        echo "Download URL: $DOWNLOAD_URL"
        
        # 下载最新版本
        wget -O fofax.tar.gz $DOWNLOAD_URL
        
        # 解压并安装
        tar -zxvf fofax.tar.gz
        sudo mv fofax /usr/local/bin/
        
        # 验证安装
        fofax -v

    - name: Run search script
      run: bash search.sh

    - name: Commit results
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add results/*
        git commit -m "Update search results" || echo "No changes to commit"
        git push
