name: Daily FoFa Search

on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  search:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install FoFaX
      run: |
        # 获取最新版本号
        LATEST_VERSION=$(curl -s https://api.github.com/repos/xiecat/fofax/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
        echo "Latest FoFaX version: $LATEST_VERSION"
        
        # 下载最新版本
        wget "https://github.com/xiecat/fofax/releases/download/${LATEST_VERSION}/fofax_${LATEST_VERSION#v}_linux_amd64.tar.gz"
        
        # 解压并安装
        tar -zxvf "fofax_$${LATEST_VERSION#v}_linux_amd64.tar.gz"
        sudo mv fofax /usr/local/bin/
        
        # 验证安装
        fofax -v

    - name: Run search script
      run: bash search.sh

    - name: Commit results
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add results/*
        git commit -m "Update search results" || echo "No changes to commit"
        git push
